import Bld1 from '../../assets/images/game/bld.png';
import Bld2 from '../../assets/images/game/bld2.png';
import Bld3 from '../../assets/images/game/bld3.png';
import Bld4 from '../../assets/images/game/bld4.png';
import Bld5 from '../../assets/images/game/bld5.png';
import Bld6 from '../../assets/images/game/bld6.png';
import Bld7 from '../../assets/images/game/bld7.png';
import Bld8 from '../../assets/images/game/bld8.png';
import Bld9 from '../../assets/images/game/bld9.png';
import Bld10 from '../../assets/images/game/bld10.png';
import Bld11 from '../../assets/images/game/bld11.png';
import Bld12 from '../../assets/images/game/bld12.png';
import Bld13 from '../../assets/images/game/bld13.png';
import Bld14 from '../../assets/images/game/bld14.png';
import Cafe1 from '../../assets/images/game/cafe1.png';
import Home1 from '../../assets/images/game/home1.png';
import Home2 from '../../assets/images/game/home2.png';
import Home3 from '../../assets/images/game/home3.png';
import Park1 from '../../assets/images/game/park.png';
import Park2 from '../../assets/images/game/park2.png';
import Park3 from '../../assets/images/game/park3.png';
import Park4 from '../../assets/images/game/park4.png';
import Park5 from '../../assets/images/game/park5.png';
import Park6 from '../../assets/images/game/park6.png';
import Park7 from '../../assets/images/game/park7.png';
import Park8 from '../../assets/images/game/park8.png';
import Park9 from '../../assets/images/game/park9.png';

export const BuildingsMenuArray = [
  {
    id: 1,
    name: 'building_1',
    title: 'Building 1',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 1000,
    imageUrl: Bld1,
  },
  {
    id: 2,
    name: 'building_2',
    title: 'Building 2',
    cost: 100,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 10000,
    imageUrl: Bld2,
  },
  {
    id: 3,
    name: 'building_3',
    title: 'Building 3',
    cost: 25,
    currencyType: 'gems',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 10000,
    imageUrl: Bld3,
  },
  {
    id: 4,
    name: 'building_4',
    title: 'Building 4',
    cost: 100,
    currencyType: 'gems',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld4,
  },
  {
    id: 5,
    name: 'building_5',
    title: 'Building 5',
    cost: 250000,
    currencyType: 'gold',
    incomeAmount: 1000,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld5,
  },
  {
    id: 6,
    name: 'building_6',
    title: 'Building 6',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld6,
  },
  {
    id: 7,
    name: 'building_7',
    title: 'Building 7',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld7,
  },
  {
    id: 8,
    name: 'building_8',
    title: 'Building 8',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld8,
  },
  {
    id: 9,
    name: 'building_9',
    title: 'Building 9',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld9,
  },
  {
    id: 10,
    name: 'building_10',
    title: 'Building 10',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld10,
  },
  {
    id: 11,
    name: 'building_11',
    title: 'Building 11',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld11,
  },
  {
    id: 12,
    name: 'building_12',
    title: 'Building 12',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld12,
  },
  {
    id: 13,
    name: 'building_13',
    title: 'Building 13',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld13,
  },
  {
    id: 14,
    name: 'building_14',
    title: 'Building 14',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Bld14,
  },
  {
    id: 15,
    name: 'cafe_1',
    title: 'Cafe 1',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Cafe1,
  },
  {
    id: 16,
    name: 'home_1',
    title: 'Home 1',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Home1,
  },
  {
    id: 17,
    name: 'home_2',
    title: 'Home 2',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Home2,
  },
  {
    id: 18,
    name: 'home_3',
    title: 'Home 3',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: '1 minute',
    incomeSeconds: 60000,
    imageUrl: Home3,
  },
  {
    id: 19,
    name: 'park_1',
    title: 'Park 1',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park1,
  },
  {
    id: 20,
    name: 'park_2',
    title: 'Park 2',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park2,
  },
  {
    id: 21,
    name: 'park_3',
    title: 'Park 3',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park3,
  },
  {
    id: 22,
    name: 'park_4',
    title: 'Park 4',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park4,
  },
  {
    id: 23,
    name: 'park_5',
    title: 'Park 5',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park5,
  },
  {
    id: 24,
    name: 'park_6',
    title: 'Park 6',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park6,
  },
  {
    id: 25,
    name: 'park_7',
    title: 'Park 7',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park7,
  },
  {
    id: 26,
    name: 'park_8',
    title: 'Park 8',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park8,
  },
  {
    id: 27,
    name: 'park_9',
    title: 'Park 9',
    cost: 25,
    currencyType: 'gold',
    incomeAmount: 10,
    incomeCurrency: 'gold',
    incomePeriod: null,
    incomeSeconds: null,
    imageUrl: Park9,
  },
];
